// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCrawler.Entities;

#nullable disable

namespace WebCrawler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebCrawler.Entities.ExecutionRecord", b =>
                {
                    b.Property<int>("ExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SiteRecordId")
                        .HasColumnType("int");

                    b.Property<int>("SitesCrawled")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ExecutionId");

                    b.HasIndex("SiteRecordId");

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("WebCrawler.Entities.Tag", b =>
                {
                    b.Property<int>("ExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("SiteRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ExecutionId");

                    b.HasIndex("SiteRecordId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("WebCrawler.Entities.WebSiteRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BoundaryRegExp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PeriodicityMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("WebSiteRecords");
                });

            modelBuilder.Entity("WebCrawler.Entities.ExecutionRecord", b =>
                {
                    b.HasOne("WebCrawler.Entities.WebSiteRecord", "SiteRecord")
                        .WithMany("Executions")
                        .HasForeignKey("SiteRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteRecord");
                });

            modelBuilder.Entity("WebCrawler.Entities.Tag", b =>
                {
                    b.HasOne("WebCrawler.Entities.WebSiteRecord", "SiteRecord")
                        .WithMany("Tags")
                        .HasForeignKey("SiteRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteRecord");
                });

            modelBuilder.Entity("WebCrawler.Entities.WebSiteRecord", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
