version: '3.4'

services:
  webcrawler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - webcrawler-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: WebCrawlerDb
      MYSQL_USER: root
      MYSQL_PASSWORD: passwd
    ports:
      - "55422:3306"
    networks:
      - webcrawler-network

networks:
  webcrawler-network:
    driver: bridge
